"""Exact dotenv reader for credentials and deployment configuration.

python-dotenv expands ``${NAME}`` sequences inside values. That is useful for
developer configuration, but unsafe for opaque passwords and tokens. Production
files generated by this project use JSON string literals, which this reader can
decode without interpolation.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

_INLINE_COMMENT_RE = re.compile(r"\s+#")


def _strip_inline_comment(raw: str) -> str:
    """Remove a dotenv inline comment while preserving a quoted literal."""
    value = raw.strip()
    if not value or value[0] not in {'"', "'"}:
        match = _INLINE_COMMENT_RE.search(value)
        return value[: match.start()].rstrip() if match is not None else value

    quote = value[0]
    escaped = False
    for index, char in enumerate(value[1:], start=1):
        if char == quote and not escaped:
            suffix = value[index + 1 :].lstrip()
            if not suffix or suffix.startswith("#"):
                return value[: index + 1]
            return value
        escaped = char == "\\" and not escaped
        if char != "\\":
            escaped = False
    return value


def _unquoted_value(raw: str) -> str:
    """Strip dotenv inline comments without expanding or unescaping the value."""
    match = _INLINE_COMMENT_RE.search(raw)
    return raw[: match.start()].rstrip() if match is not None else raw


def read_exact_env_file(path: str | Path) -> dict[str, str]:
    """Read KEY=VALUE pairs without variable or shell expansion."""
    values: dict[str, str] = {}
    for raw_line in Path(path).read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line.removeprefix("export ").lstrip()
        key, separator, raw_value = line.partition("=")
        key = key.strip()
        if not separator or not key:
            continue
        value = _strip_inline_comment(raw_value)
        if value.startswith('"'):
            try:
                decoded = json.loads(value)
            except json.JSONDecodeError:
                decoded = value.strip('"')
            values[key] = str(decoded)
        elif len(value) >= 2 and value[0] == value[-1] == "'":
            values[key] = value[1:-1].replace("\\'", "'").replace("\\\\", "\\")
        else:
            values[key] = _unquoted_value(value)
    return values
